apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-backend
        image: divyapatel42/ecommerce-webapp:backendv1
        env:
        - name: DATABASE
          value: "mongodb://root:example@mongodb-0.mongodb.default.svc.cluster.local:27017/Ecommerce?authSource=admin"

