# Here is the deployment file for the frontend. I've set up 2 replicas, meaning 2 pods/containers will be created for the frontend.
# In the environment variables, I provided the backend connection URL to connect to the nodejs Backend.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2    # Number of Frontend replicas
  selector:
    matchLabels:
      app: react-frontend   # Label selector used by the deployment and service to manage Pods
  template:
    metadata:
      labels:
        app: react-frontend   # Labels applied to the Pods created by the Deployments
    spec:
      containers:
      - name: node-backend
        image: divyapatel42/ecommerce-webapp:frontendv1
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "https://kbackend.devopswithdivya.me"
