apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus
spec:
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30016
  type: NodePort
  selector:
    app: alertmanager

