# This is the alertmanager service file that uses a NodePort type of service. A NodePort service reserves a port on the node machine,
# allowing us to access the service using the node's IP address and the reserved port. Ex: http://<node-public-ip>:port 
# to access alertmanager from my brwoser, I chose the NodePort type of service.
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30016
  type: NodePort
  selector:
    app: alertmanager

