apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30013
  type: NodePort
  selector:
    app: grafana
