apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: prometheus
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30011
    - name: telemetry
      port: 8081
      targetPort: 8081
      nodePort: 30012
  type: NodePort
  selector:
    app: kube-state-metrics
