apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager.prometheus.svc.cluster.local:9093']
    rule_files:
      - /etc/prometheus/alerting-rules.yaml
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: kube-state-metrics
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        metrics_path: /metrics
        scheme: http
        static_configs:
        - targets:
          - kube-state-metrics.prometheus.svc.cluster.local:8080

  alerting-rules.yaml: |
    groups:
    - name: Infrastuctutre alerts
      rules:
      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready", status="false"} == 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Node {{ $labels.node }} is not ready"
          description: "Node {{ $labels.node }} has been in a NotReady state for more than 5 minutes."
      - alert: LowNodeMemory
        expr: kube_node_status_allocatable{resource="memory"} < 1 * 1024 * 1024 * 1024  # less than 1 GB
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Node {{ $labels.node }} has low allocatable memory"
          description: "Node {{ $labels.node }} has less than 1GB of allocatable memory."

