apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: aws-ebs-gp2
